---
abstract: 'Perl interface to y.ahoo.it'
author:
  - 'Charles A. Wimmer <charles@wimmer.net>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Pod::Coverage::TrustPod: 0
  TAP::Formatter::JUnit: 0
  TAP::Harness::JUnit: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-Yahooit
requires:
  Carp: 0
  Exporter: 0
  WWW::Shorten::generic: 0
  WWW::YQL: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/cwimmer/WWW-Shorten-Yahooit.git
version: 0.004
